[workspace]
#default-members = ["crates/cli"]
members = [
    "crates/catalog",
    "crates/common",
    "crates/cli",
    "crates/web",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["CarloMicieli <piovarolo@gmail.com>"]
license = "Apache-2.0"
rust-version = "1.66"

[workspace.dependencies]
actix-web = "4"
anyhow = "1.0"
chrono = { version = "0.4.23", features = ["serde"] }
clap = "4.0.26"
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
http = "0.2.8"
isocountry = "0.3.2"
itertools = "0.10.5"
log = "0.4"
pretty_assertions = "1.3.0"
rstest = "0.16.0"
rust_decimal = "1.27.0"
rust_decimal_macros = "1.27.0"
secrecy = { version = "0.8", features = ["serde"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_derive = "1.0.148"
serde_json = "1.0.87"
serde_yaml = "0.9.14"
slug = "0.1.4"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"
tracing = "0.1.37"
tracing-actix-web = "0.7"
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.2.1", features = ["serde", "v4"] }

[workspace.dependencies.sqlx]
version = "0.6.2"
default-features = false
features = [
    "chrono",
    "macros",
    "migrate",
    "offline",
    "postgres",
    "runtime-tokio-rustls",
    "uuid"
]
