[workspace]
members = [
    "crates/catalog",
    "crates/cli",
    "crates/common",
    "crates/server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["CarloMicieli <piovarolo@gmail.com>"]
license = "Apache-2.0"
rust-version = "1.67"

[workspace.dependencies]
actix-web = "4.3.0"
anyhow = "1.0.69"
async-trait = "0.1.64"
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.1.6", features = ["derive"] }
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
dockertest = { git = "https://github.com/orcalabs/dockertest-rs", rev = "7e0a718", features = ["tls"] }
http = "0.2.8"
isocountry = "0.3.2"
itertools = "0.10.5"
jsonschema = "0.16.1"
log = "0.4.17"
once_cell = "1.17.1"
pretty_assertions = "1.3.0"
rand = "0.8.5"
reqwest = { version = "0.11.14", features = ["json"] }
rstest = "0.16.0"
rust_decimal = { version = "1.28.1", features = ["serde-with-float"] }
rust_decimal_macros = "1.28.1"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_derive = "1.0.152"
serde_json = "1.0.93"
slug = "0.1.4"
strum = "0.24.1"
strum_macros = "0.24.1"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-actix-web = "0.7.2"
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["registry", "env-filter"] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.3.0", features = ["serde", "v4"] }
validator = { version = "0.16.0", features = ["derive", "phone"] }
walkdir = "2.3.2"

[workspace.dependencies.sqlx]
version = "0.6.2"
default-features = false
features = [
    "chrono",
    "decimal",
    "macros",
    "migrate",
    "offline",
    "postgres",
    "runtime-tokio-rustls",
    "uuid"
]

[workspace.dependencies.fake]
version = "2.5.0"
default-features = false
features = [
    "chrono",
    "rust_decimal",
    "uuid"
]
