[workspace]
#default-members = ["crates/cli"]
members = [
    "crates/catalog",
    "crates/common",
    "crates/cli",
    "crates/web",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["CarloMicieli <piovarolo@gmail.com>"]
license = "Apache-2.0"
rust-version = "1.65"

[workspace.dependencies]
actix-web = "4"
anyhow = "1.0.66"
chrono = "0.4.23"
clap = "4.0.26"
isocountry = "0.3.2"
itertools = "0.10.5"
pretty_assertions = "1.3.0"
rust_decimal = "1.27.0"
rust_decimal_macros = "1.27.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
slug = "0.1.4"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.37"
url = "2.3.1"
uuid = { version = "1.2.1", features = ["serde", "v4"] }
