[workspace]
members = [
    "crates/catalog",
    "crates/cli",
    "crates/common",
    "crates/configuration",
    "crates/data",
    "crates/server",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["CarloMicieli <piovarolo@gmail.com>"]
license = "Apache-2.0"
rust-version = "1.73"

[workspace.dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
axum = "0.6.20"
axum-macros = "0.3.8"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.7", features = ["derive"] }
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
dockertest = { git = "https://github.com/orcalabs/dockertest-rs", rev = "7e0a718", features = ["tls"] }
http = "0.2.9"
hyper = { version = "0.14.27", features = ["http1", "server"] }
isocountry = "0.3.2"
itertools = "0.11.0"
jsonschema = "0.17.1"
lazy_static = "1.4.0"
log = "0.4.20"
mime = "0.3.17"
once_cell = "1.18.0"
pretty_assertions = "1.4.0"
rand = "0.8.5"
regex = "1.10.2"
reqwest = { version = "0.11.22", features = ["json"] }
rstest = "0.18.2"
rust_decimal = { version = "1.32.0", features = ["serde-with-float"] }
rust_decimal_macros = "1.32.0"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_derive = "1.0.190"
serde_json = "1.0.107"
serde_urlencoded = "0.7.1"
slug = "0.1.4"
strum = "0.25.0"
strum_macros = "0.25.3"
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["limit", "timeout"] }
tower-http = { version = "0.4.4", features = ["compression-gzip", "propagate-header", "request-id", "trace"] }
tracing = "0.1.40"
tracing-bunyan-formatter = "0.3.9"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.17", features = ["registry", "env-filter", "json"] }
url = { version = "2.4.1", features = ["serde"] }
uuid = { version = "1.5.0", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive", "phone"] }
walkdir = "2.4.0"

[workspace.dependencies.sqlx]
version = "0.7.2"
default-features = false
features = [
    "chrono",
    "rust_decimal",
    "macros",
    "migrate",
    "postgres",
    "runtime-tokio-rustls",
    "uuid"
]

[workspace.dependencies.fake]
version = "2.9.1"
default-features = false
features = [
    "chrono",
    "rust_decimal",
    "uuid"
]

[profile.dev.package.sqlx-macros]
opt-level = 3
