[workspace]
members = [
    "crates/catalog",
    "crates/cli",
    "crates/common",
    "crates/db",
    "crates/server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["CarloMicieli <piovarolo@gmail.com>"]
license = "Apache-2.0"
rust-version = "1.69"

[workspace.dependencies]
actix-web = "4.3.1"
anyhow = "1.0.71"
async-trait = "0.1.68"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.3.0", features = ["derive"] }
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
dockertest = { git = "https://github.com/orcalabs/dockertest-rs", rev = "7e0a718", features = ["tls"] }
http = "0.2.9"
isocountry = "0.3.2"
itertools = "0.10.5"
jsonschema = "0.17.0"
lazy_static = "1.4.0"
log = "0.4.17"
mime = "0.3.17"
once_cell = "1.17.1"
pretty_assertions = "1.3.0"
rand = "0.8.5"
regex = "1.8.2"
reqwest = { version = "0.11.18", features = ["json"] }
rstest = "0.17.0"
rust_decimal = { version = "1.29.1", features = ["serde-with-float"] }
rust_decimal_macros = "1.29.1"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_derive = "1.0.163"
serde_json = "1.0.96"
serde_urlencoded = "0.7.1"
slug = "0.1.4"
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-actix-web = "0.7.4"
tracing-bunyan-formatter = "0.3.7"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = ["registry", "env-filter"] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.3.3", features = ["serde", "v4"] }
validator = { version = "0.16.0", features = ["derive", "phone"] }
walkdir = "2.3.3"

[workspace.dependencies.sqlx]
version = "0.6.3"
default-features = false
features = [
    "chrono",
    "decimal",
    "macros",
    "migrate",
    "offline",
    "postgres",
    "runtime-tokio-rustls",
    "uuid"
]

[workspace.dependencies.fake]
version = "2.6.1"
default-features = false
features = [
    "chrono",
    "rust_decimal",
    "uuid"
]

[profile.dev.package.sqlx-macros]
opt-level = 3
