[workspace]
#default-members = ["crates/cli"]
members = [
    "crates/catalog",
    "crates/common",
    "crates/cli",
    "crates/web",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["CarloMicieli <piovarolo@gmail.com>"]
license = "Apache-2.0"
rust-version = "1.65"

[workspace.dependencies]
actix-web = "4"
anyhow = "1.0.66"
clap = "4.0.26"
isocountry = "0.3.2"
pretty_assertions = "1.3.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
slug = "0.1.4"
thiserror = "1.0.37"
