[workspace]
members = [
    "crates/catalog",
    "crates/cli",
    "crates/common",
    "crates/configuration",
    "crates/db",
    "crates/hateoas",
    "crates/problem",
    "crates/server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["CarloMicieli <piovarolo@gmail.com>"]
license = "Apache-2.0"
rust-version = "1.71"

[workspace.dependencies]
actix-web = "4.3.1"
anyhow = "1.0.72"
async-trait = "0.1.72"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.19", features = ["derive"] }
config = { version = "0.13.3", default-features = false, features = ["yaml"] }
dockertest = { git = "https://github.com/orcalabs/dockertest-rs", rev = "7e0a718", features = ["tls"] }
http = "0.2.9"
isocountry = "0.3.2"
itertools = "0.11.0"
jsonschema = "0.17.1"
lazy_static = "1.4.0"
log = "0.4.19"
mime = "0.3.17"
once_cell = "1.18.0"
pretty_assertions = "1.4.0"
rand = "0.8.5"
regex = "1.9.1"
reqwest = { version = "0.11.18", features = ["json"] }
rstest = "0.18.1"
rust_decimal = { version = "1.30.0", features = ["serde-with-float"] }
rust_decimal_macros = "1.30.0"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.175", features = ["derive"] }
serde_derive = "1.0.175"
serde_json = "1.0.103"
serde_urlencoded = "0.7.1"
slug = "0.1.4"
strum = "0.25.0"
strum_macros = "0.25.1"
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-actix-web = "0.7.5"
tracing-bunyan-formatter = "0.3.8"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = ["registry", "env-filter"] }
url = { version = "2.4.0", features = ["serde"] }
uuid = { version = "1.4.1", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive", "phone"] }
walkdir = "2.3.3"

[workspace.dependencies.sqlx]
version = "0.7.1"
default-features = false
features = [
    "chrono",
    "rust_decimal",
    "macros",
    "migrate",
    "postgres",
    "runtime-tokio-rustls",
    "uuid"
]

[workspace.dependencies.fake]
version = "2.6.1"
default-features = false
features = [
    "chrono",
    "rust_decimal",
    "uuid"
]

[profile.dev.package.sqlx-macros]
opt-level = 3
