version: "3.9"

services:
  db:
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: trenakodb
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ CMD-SHELL, 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./.config/pgadmin/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./.config/pgadmin/pgpass:/pgpass # passwords for the connections in this file
    networks:
      - backend

  api:
    image: trenako-server:latest
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5000
      SERVER_WORKERS: 4
      DATABASE_NAME: trenakodb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: mysecretpassword
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - 5000:5000
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:5000/health_check || exit 1
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 5

networks:
  backend:

volumes:
  db-data:
