use actix_web::{web, HttpResponse, Responder};

pub fn config_services(cfg: &mut web::ServiceConfig) {
    #[rustfmt::skip]
    cfg.service(
        web::scope("/api")
            .service(
                web::scope("/brands")
                    .service(
                        web::resource("")
                            .route(web::get().to(todo))
                            .route(web::post().to(todo))
                    )
                    .service(
                        web::resource("/{brand}")
                            .route(web::delete().to(todo))
                            .route(web::get().to(todo))
                            .route(web::put().to(todo))
                    )
            )
            .service(
                web::scope("/catalog-items")
                    .service(
                        web::resource("")
                            .route(web::post().to(todo))
                    )
                    .service(
                        web::scope("/{catalog_item_id}")
                            .service(
                                web::resource("")
                                    .route(web::delete().to(todo))
                                    .route(web::get().to(todo))
                                    .route(web::put().to(todo))
                            )
                            .service(
                                web::scope("/rolling-stocks")
                                    .service(
                                        web::resource("")
                                            .route(web::get().to(todo))
                                            .route(web::post().to(todo))
                                    )
                                    .service(
                                        web::resource("/{rolling_stock_id}")
                                            .route(web::delete().to(todo))
                                            .route(web::get().to(todo))
                                            .route(web::put().to(todo))
                                    )
                            )
                    )
            )
            .service(
                web::scope("/railways")
                    .service(
                        web::resource("")
                            .route(web::get().to(todo))
                            .route(web::post().to(todo))
                    )
                    .service(
                        web::resource("/{railway}")
                            .route(web::delete().to(todo))
                            .route(web::get().to(todo))
                            .route(web::put().to(todo))
                    )
            )
            .service(
                web::scope("/scales")
                    .service(
                        web::resource("")
                            .route(web::get().to(todo))
                            .route(web::post().to(todo))
                    )
                    .service(
                        web::resource("/{scale}")
                            .route(web::delete().to(todo))
                            .route(web::get().to(todo))
                            .route(web::put().to(todo))
                    )
            )
    );
}

pub async fn todo() -> impl Responder {
    HttpResponse::InternalServerError().body("not implements")
}
