server:
  host: 127.0.0.1
  port: 5000
database:
  host: 127.0.0.1
  port: 5432
  name: trenakodb
  username: postgres
  password: mysecretpassword
  min_connections: 1
  max_connections: 10
  require_ssl: false
logging:
  format: compact
  level: debug
