use crate::catalog::handlers::{brands, catalog_items, railways, scales};
use actix_web::web;

pub fn config_services(cfg: &mut web::ServiceConfig) {
    #[rustfmt::skip]
    cfg.service(
        web::scope("/api")
            .service(
                web::scope("/brands")
                    .service(
                        web::resource("")
                            .route(web::get().to(brands::get_all_brands))
                            .route(web::post().to(brands::post_brand))
                    )
                    .service(
                        web::resource("/{brand}")
                            .route(web::delete().to(brands::delete_brand))
                            .route(web::get().to(brands::get_brand_by_id))
                            .route(web::put().to(brands::delete_brand))
                    )
            )
            .service(
                web::scope("/catalog-items")
                    .service(
                        web::resource("")
                            .route(web::post().to(catalog_items::post_catalog_item))
                    )
                    .service(
                        web::scope("/{catalog_item_id}")
                            .service(
                                web::resource("")
                                    .route(web::delete().to(catalog_items::delete_catalog_item))
                                    .route(web::get().to(catalog_items::get_catalog_item_by_id))
                                    .route(web::put().to(catalog_items::put_catalog_item))
                            )
                            .service(
                                web::scope("/rolling-stocks")
                                    .service(
                                        web::resource("")
                                            .route(web::get().to(catalog_items::get_rolling_stock_by_id))
                                            .route(web::post().to(catalog_items::post_rolling_stock))
                                    )
                                    .service(
                                        web::resource("/{rolling_stock_id}")
                                            .route(web::delete().to(catalog_items::delete_rolling_stock))
                                            .route(web::get().to(catalog_items::get_rolling_stock_by_id))
                                            .route(web::put().to(catalog_items::put_rolling_stock))
                                    )
                            )
                    )
            )
            .service(
                web::scope("/railways")
                    .service(
                        web::resource("")
                            .route(web::get().to(railways::get_all_railways))
                            .route(web::post().to(railways::post_railway))
                    )
                    .service(
                        web::resource("/{railway}")
                            .route(web::delete().to(railways::delete_railway))
                            .route(web::get().to(railways::get_railway_by_id))
                            .route(web::put().to(railways::put_railway))
                    )
            )
            .service(
                web::scope("/scales")
                    .service(
                        web::resource("")
                            .route(web::get().to(scales::get_all_scales))
                            .route(web::post().to(scales::post_scale))
                    )
                    .service(
                        web::resource("/{scale}")
                            .route(web::delete().to(scales::delete_scale))
                            .route(web::get().to(scales::get_scale_by_id))
                            .route(web::put().to(scales::put_scale))
                    )
            )
    );
}
