[package]
name = "common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
slug = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
