spring:
  application:
    name: e2e-api
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/roundhouse
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 10
      max-size: 25

logging:
  level:
    org.springframework: INFO
    io.github.carlomicieli.trenako: INFO
