spring:
  application:
    name: e2e-api
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 15
logging:
  level:
    org.springframework: INFO
