name: db-migrations

on:
  push:
    paths:
      - '.sqlx/**'
      - 'migrations/**'
  workflow_dispatch:

env:
  DATABASE_URL: postgresql://postgres:mysecretpassword@127.0.0.1:5432/trenakodb

jobs:
  validate:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:18.1-alpine3.23@sha256:b40d931bd0e7ce6eecc59a5a6ac3b3c04a01e559750e73e7086b6dbd7f8bf545
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: trenakodb
        ports:
          - 5432:5432

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup the rust toolchain
        uses: dtolnay/rust-toolchain@1.95.0

      - name: Install sqlx cli
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        continue-on-error: false

      - name: Toolchain info
        run: |
          rustc --version
          cargo --version --verbose
          sqlx --version

      - name: List available migrations
        run: cargo sqlx migrate info

      - name: List the database migrations to apply
        run: cargo sqlx migrate run --dry-run

      - name: Run the database migrations (up)
        run: cargo sqlx migrate run

      - name: Validate sqlx offline metadata
        run: cargo sqlx prepare --check --workspace

      - name: List the database migrations to revert
        run: cargo sqlx migrate revert --dry-run --target-version 0

      - name: Run the database migrations (down)
        run: cargo sqlx migrate revert --target-version 0
