name: dev

on:
  push:
    branches: 
      - dev
    paths:
      - '.github/workflows/dev.yml'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'crates/**'
      - 'rust-toolchain.toml'
      - 'rustfmt.toml'
      - 'sqlx-data.json'
      - 'migrations/**'
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_MAKE_RUN_CODECOV: true

jobs:
  checks:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          cargo install --force cargo-make

      - name: Toolchain info
        run: |
          rustc --version
          cargo --version --verbose

      - name: Run cargo check
        run: cargo make check

      - name: Check formatting with rustfmt
        run: cargo make format

      - name: Linting with Clippy
        run: cargo make clippy

      - name: Run tests
        run: cargo make test

      - name: Run cargo-tarpaulin
        run: cargo make code-coverage

      - name: Upload coverage to Codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
