name: trenako-cli

on:
  push:
    paths:
      - '.github/workflows/trenako-cli.yml'
      - 'tools/**'
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./tools

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with: 
          build-root-directory: ./tools

      - name: Compile the project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x check
          build-root-directory: ./tools

      - name: Checks that sourcecode satisfies formatting rules
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck
          build-root-directory: ./tools

      - name: Run the unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: ./tools
